export enum ActionType {
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    SETSTRUCT = 'SETSTRUCT',
    SETSTRUCTNAME = 'SETSTRUCTNAME',
    SETSTRUCTDATA = 'SETSTRUCTDATA',
    SETTYPE = 'SETTYPE',
    SETCODELOGOPERATION = 'SETCODELOGOPERATION',
    SETCODE = 'SETCODE',
    SETLOG = 'SETLOG',
    SETOPERATION = 'SETOPERATION',
    SETLOGOPERATION = 'SETLOGOPERATION',
    SETNODE = 'SETNODE',
    OPENNODEINDEX = 'OPENNODEINDEX',
    OPENTOOLINDEX = 'OPENTOOLINDEX',
    EDITNODEINDEX = 'EDITNODEINDEX',
    CLOSEDETAILINDEX = 'CLOSEDETAILINDEX'
}